# Generated by Django 5.0.2 on 2024-05-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breadandcake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
