# Generated by Django 5.0.2 on 2024-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadandcake', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
